name: Build Indexer

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from (not needed when triggered by tag push)'
        required: false
        default: 'main'
      tag:
        description: 'Tag name for the Docker image (optional)'
        required: false
      environment:
        description: 'Environment to tag with (when not using custom tag)'
        required: false
        default: 'celestia-prod'
        type: choice
        options:
          # mainnet
          - celestia-prod
          - story-prod
          - berachain-prod
          - nillion-prod
          - asi

          # testnet
          - 0g-testnet-prod
          - nillion-testnet-prod
          - story-testnet-prod
          - babylon-testnet-prod

          # dev
          - celestia-dev
      deploy_after_build:
        description: 'Deploy this image after building'
        required: false
        default: false
        type: boolean
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'celestia-prod' }}
    outputs:
      IMAGE_TAG: ${{ steps.build.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Choose go.mod file
        run: |
          GO_MOD_FILE=${{ vars.GO_MOD_FILE || 'go.mod.or' }}
          if [ "$GO_MOD_FILE" != "go.mod" ]; then
            mv $GO_MOD_FILE go.mod
          fi

      - name: Run go mod tidy
        run: |
          go mod tidy
          if [[ "${{ vars.BASE_INDEX_EVM_TRANSACTIONS }}" != "true" ]]; then
            go mod vendor
          fi

      - name: Build Docker Image
        id: build
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            IMAGE_TAG=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
            echo "Using tag from Git: ${IMAGE_TAG}"
          elif [ -n "${{ github.event.inputs.tag }}" ]; then
            IMAGE_TAG="${{ github.event.inputs.tag }}"
            echo "Using provided tag: ${IMAGE_TAG}"
          else
            BRANCH_NAME=$(echo "${{ github.event.inputs.branch }}" | tr '/' '-')
            IMAGE_TAG="${BRANCH_NAME}-${{ github.event.inputs.environment }}"
            echo "Using branch-environment tag: ${IMAGE_TAG}"
          fi
          sudo docker build -t ghcr.io/${{ github.repository }}/cosmos-indexer:${IMAGE_TAG} --build-arg TARGETPLATFORM=linux/amd64 .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Push Docker Image
        run: |
          sudo docker push ghcr.io/${{ github.repository }}/cosmos-indexer:${{ steps.build.outputs.IMAGE_TAG }}
      
      - name: Create Deployment Summary
        run: |
          echo "## ✅ Image build completed" >> $GITHUB_STEP_SUMMARY
          echo -e "**Image tag:**\n\`\`\`\n${{ steps.build.outputs.IMAGE_TAG }}\n\`\`\`" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event.inputs.deploy_after_build }}" == "true" ]; then
            echo "Image will be automatically deployed to ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "To deploy this image, you can:" >> $GITHUB_STEP_SUMMARY
            echo "1. Run this workflow again with the 'Deploy this image after building' option checked" >> $GITHUB_STEP_SUMMARY
            echo "   - Use the same branch and environment" >> $GITHUB_STEP_SUMMARY
            echo "   - Enter '${{ steps.build.outputs.IMAGE_TAG }}' as the tag name" >> $GITHUB_STEP_SUMMARY
            echo "2. Or manually trigger the deployment workflow:" >> $GITHUB_STEP_SUMMARY
            echo "   - Go to the Actions tab" >> $GITHUB_STEP_SUMMARY
            echo "   - Select 'Deploy Indexer - PROD'" >> $GITHUB_STEP_SUMMARY
            echo "   - Use the tag shown above in the 'Docker image tag to deploy' field" >> $GITHUB_STEP_SUMMARY
          fi

  deploy:
    needs: build
    if: ${{ github.event.inputs.deploy_after_build == 'true' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      image_tag: ${{ needs.build.outputs.IMAGE_TAG }}
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit
